# Default skill library for SkillTreeEvolver

DEFAULT_SKILLS = [
    # Root categories
    {
        "skill_id": "coding",
        "name": "Coding",
        "description": "Software development and programming skills",
        "category": "coding",
        "level": 1, "xp_required": 100, "xp_current": 0,
        "parent_id": None, "children_ids": [],
        "dependencies": [], "tags": ["dev", "programming"],
    },
    {
        "skill_id": "reasoning",
        "name": "Reasoning",
        "description": "Logical analysis and problem-solving skills",
        "category": "reasoning",
        "level": 1, "xp_required": 100, "xp_current": 0,
        "parent_id": None, "children_ids": [],
        "dependencies": [], "tags": ["logic", "analysis"],
    },
    {
        "skill_id": "research",
        "name": "Research",
        "description": "Information gathering and synthesis skills",
        "category": "research",
        "level": 1, "xp_required": 100, "xp_current": 0,
        "parent_id": None, "children_ids": [],
        "dependencies": [], "tags": ["search", "analysis"],
    },
    {
        "skill_id": "writing",
        "name": "Writing",
        "description": "Content creation and documentation skills",
        "category": "writing",
        "level": 1, "xp_required": 100, "xp_current": 0,
        "parent_id": None, "children_ids": [],
        "dependencies": [], "tags": ["content", "docs"],
    },
    # Coding children
    {
        "skill_id": "code_review",
        "name": "Code Review",
        "description": "Analyzing and reviewing source code quality",
        "category": "coding",
        "level": 1, "xp_required": 80, "xp_current": 0,
        "parent_id": "coding", "children_ids": [],
        "dependencies": [], "tags": ["review", "quality"],
    },
    {
        "skill_id": "bug_fixing",
        "name": "Bug Fixing",
        "description": "Identifying and resolving software defects",
        "category": "coding",
        "level": 1, "xp_required": 80, "xp_current": 0,
        "parent_id": "coding", "children_ids": [],
        "dependencies": [], "tags": ["debug", "fix"],
    },
    {
        "skill_id": "refactoring",
        "name": "Refactoring",
        "description": "Improving code structure without changing behavior",
        "category": "coding",
        "level": 1, "xp_required": 120, "xp_current": 0,
        "parent_id": "coding", "children_ids": [],
        "dependencies": ["code_review"], "tags": ["restructure", "quality"],
    },
    {
        "skill_id": "testing",
        "name": "Testing",
        "description": "Writing and executing automated tests",
        "category": "coding",
        "level": 1, "xp_required": 80, "xp_current": 0,
        "parent_id": "coding", "children_ids": [],
        "dependencies": [], "tags": ["test", "qa"],
    },
    {
        "skill_id": "api_design",
        "name": "API Design",
        "description": "Designing clean and intuitive APIs",
        "category": "coding",
        "level": 1, "xp_required": 120, "xp_current": 0,
        "parent_id": "coding", "children_ids": [],
        "dependencies": [], "tags": ["api", "design"],
    },
    # Reasoning children
    {
        "skill_id": "problem_decomposition",
        "name": "Problem Decomposition",
        "description": "Breaking complex problems into manageable parts",
        "category": "reasoning",
        "level": 1, "xp_required": 80, "xp_current": 0,
        "parent_id": "reasoning", "children_ids": [],
        "dependencies": [], "tags": ["decomposition", "planning"],
    },
    {
        "skill_id": "root_cause",
        "name": "Root Cause Analysis",
        "description": "Finding the underlying cause of issues",
        "category": "reasoning",
        "level": 1, "xp_required": 100, "xp_current": 0,
        "parent_id": "reasoning", "children_ids": [],
        "dependencies": [], "tags": ["analysis", "diagnosis"],
    },
    {
        "skill_id": "decision_making",
        "name": "Decision Making",
        "description": "Evaluating options and making informed choices",
        "category": "reasoning",
        "level": 1, "xp_required": 100, "xp_current": 0,
        "parent_id": "reasoning", "children_ids": [],
        "dependencies": [], "tags": ["choice", "strategy"],
    },
    # Research children
    {
        "skill_id": "web_search",
        "name": "Web Search",
        "description": "Efficiently finding information online",
        "category": "research",
        "level": 1, "xp_required": 60, "xp_current": 0,
        "parent_id": "research", "children_ids": [],
        "dependencies": [], "tags": ["search", "info"],
    },
    {
        "skill_id": "document_synthesis",
        "name": "Document Synthesis",
        "description": "Combining information from multiple sources",
        "category": "research",
        "level": 1, "xp_required": 100, "xp_current": 0,
        "parent_id": "research", "children_ids": [],
        "dependencies": [], "tags": ["synthesis", "summary"],
    },
    # Writing children
    {
        "skill_id": "technical_docs",
        "name": "Technical Documentation",
        "description": "Writing clear technical documentation",
        "category": "writing",
        "level": 1, "xp_required": 80, "xp_current": 0,
        "parent_id": "writing", "children_ids": [],
        "dependencies": [], "tags": ["docs", "technical"],
    },
    {
        "skill_id": "creative_writing",
        "name": "Creative Writing",
        "description": "Generating engaging creative content",
        "category": "writing",
        "level": 1, "xp_required": 100, "xp_current": 0,
        "parent_id": "writing", "children_ids": [],
        "dependencies": [], "tags": ["creative", "content"],
    },
    {
        "skill_id": "translation",
        "name": "Translation",
        "description": "Translating content between languages",
        "category": "writing",
        "level": 1, "xp_required": 100, "xp_current": 0,
        "parent_id": "writing", "children_ids": [],
        "dependencies": [], "tags": ["language", "translate"],
    },
]
